---
apiVersion: v1
kind: Service
metadata:
  name: online-game-server
spec:
  selector:
    app: online-game-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
