---
version: "3"
services:
  client:
    build:
      dockerfile: ./build/client/Dockerfile
      context: .
    image: client
    container_name: client
    ports:
      - 8080:8080
  server:
    build:
      dockerfile: ./build/server/Dockerfile
      context: .
    image: server
    container_name: server
