---
version: "3"
services:
  client:
    build:
      dockerfile: ./docker/client/Dockerfile
      context: .
    image: ghcr.io/gcleroux/online-game-client:latest
    container_name: local-client
    ports:
      - 8080:8080

  server:
    build:
      dockerfile: ./docker/server/Dockerfile
      context: .
    image: ghcr.io/gcleroux/online-game-server:latest
    container_name: local-server
    ports:
      - 8888:8080

  # The kind services are used for local k8s testing with kind
  kind-client:
    build:
      dockerfile: ./docker/client/Dockerfile
      context: .
    image: localhost:5001/online-game-client:v1
    container_name: kind-client
    ports:
      - "8080"
  kind-server:
    build:
      dockerfile: ./docker/server/Dockerfile
      context: .
    image: localhost:5001/online-game-server:v1
    container_name: kind-server
    ports:
      - "8080"
