---
version: "3"
services:
  client:
    build:
      args:
        # Change this URL to your local IP to allow
        # access from different devices
        SERVER_URL: "http://localhost/server"
      dockerfile: ./docker/client/Dockerfile
      context: .
    image: localhost:5001/online-client:v1
    container_name: client
    ports:
      - "8080"

  server:
    build:
      dockerfile: ./docker/server/Dockerfile
      context: .
    image: localhost:5001/online-server:v1
    container_name: server
    ports:
      - "8080"
