---
version: "3"
services:
  client:
    build:
      args:
        # Change this URL to your local IP to allow
        # access from different devices
        SERVER_URL: "http://localhost:8888"
      dockerfile: ./docker/client/Dockerfile
      context: .
    image: ghcr.io/gcleroux/online-game-client:latest
    container_name: client
    ports:
      - 8080:8080

  server:
    build:
      dockerfile: ./docker/server/Dockerfile
      context: .
    image: ghcr.io/gcleroux/online-game-server:latest
    container_name: server
    ports:
      - 8888:8080
