---
version: "3"
services:
  client:
    build:
      dockerfile: ./docker/client/Dockerfile
      context: .
    image: client
    container_name: client
    ports:
      - 8080:8080
  server:
    build:
      dockerfile: ./docker/server/Dockerfile
      context: .
    image: server
    container_name: server
    ports:
      - 8888:8080
