---
remote_address: localhost
port: 8888
route: /join

connection:
  send_timeout: 500ms
  read_timeout: 500ms
  idle_timeout: 10000ms

  # The connection manager can be up to 3 frames late
  # to send data to the server without slowing down
  buffer_size: 3
