---
remote_address: 34.118.225.103
port: 8080
route: /ws

connection:
  send_timeout: 20ms
  read_timeout: 20ms
  idle_timeout: 10000ms

  # The connection manager can be up to 3 frames late
  # to send data to the server without slowing down
  buffer_size: 3
