---
version: "3"
services:
  answer:
    container_name: answer
    build: ./answer
    command: ./answer -offer-address offer:50000

  offer:
    container_name: offer
    depends_on:
      - answer
    build: ./offer
    command: ./offer -answer-address answer:60000

  rtc-client:
    build:
      dockerfile: Dockerfile.client
      context: .
    image: rtc-client
    container_name: rtc-client
    ports:
      - 8081:8081

  rtc-server:
    build:
      dockerfile: Dockerfile.server
      context: .
    image: rtc-server
    container_name: rtc-server
    ports:
      - 8080:8080
