---
name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test-build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.x

      - name: Install dependencies
        run: go mod download

      # - name: Run tests with race detector
      #   run: go test -race .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        run: |
          docker compose build client server
          docker compose push client server
          docker tag ghcr.io/gcleroux/online-game-client:latest ghcr.io/gcleroux/online-game-client:${{ github.sha }}
          docker tag ghcr.io/gcleroux/online-game-server:latest ghcr.io/gcleroux/online-game-server:${{ github.sha }}
          docker push ghcr.io/gcleroux/online-game-client:${{ github.sha }}
          docker push ghcr.io/gcleroux/online-game-server:${{ github.sha }}
